print("All Spade:")
print(Deck.allSpades)
print("\nAll Diamonds:")
print(Deck.allDiamonds)
print("\nAll Hearts:")
print(Deck.allHearts)
print("\nAll Clubs:")
print(Deck.allClubs)
print("\nAll Cards:")
print(Deck.allCards)
